name: pythonapp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-docker@v2
    - run: docker build Dockerfile .
      working-directory: /home/runner/work/Evaluation/
