name: pythonapp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build -- file Dockerfile
      working-directory: /home/runner/work/Evaluation_120623/Evaluation_120623/
