name: pythonapp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build -t ./apppy .
      working-directory: ./home/runner/work/Evaluation/
      

